AppBundle\Entity\goal:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\goalRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userId:
            type: integer
            column: user_id
        name:
            type: string
            length: 255
        dateStart:
            type: datetime
            column: date_start
        dateCompleted:
            type: datetime
            column: date_completed
        targetDateComplete:
            type: datetime
            column: target_date_complete
    lifecycleCallbacks: {  }
