AppBundle\Entity\milestone:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\milestoneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        goalId:
            type: integer
            column: goal_id
        typeId:
            type: integer
            column: type_id
        name:
            type: string
            length: 255
        percentOfGoal:
            type: integer
            column: percent_of_goal
        currentProgress:
            type: string
            length: 255
            column: current_progress
        target:
            type: integer
        targetDate:
            type: datetime
            column: target_date
    lifecycleCallbacks: {  }
