AppBundle\Entity\name:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\nameRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
