<?php

namespace AppBundle\Repository;

/**
 * goalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class goalRepository extends \Doctrine\ORM\EntityRepository
{
}
