<?php

namespace AppBundle\Repository;

/**
 * milestone_historyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class milestone_historyRepository extends \Doctrine\ORM\EntityRepository
{
}
