<?php

namespace AppBundle\Repository;

/**
 * milestoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class milestoneRepository extends \Doctrine\ORM\EntityRepository
{
}
